### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by hanyska** [SunnyApp/flutter_phone_state#14]
Please migrate this plugin to null safety. Thank you.

**Comment by BirjuVachhani** [comment]
Any updates on this? I really need this to be null safe.

**Comment by mr-mmmmore** [comment]
What are the plans for this migration? It is kind of required for any package to avoid becoming obsolete soon.

**Comment by hanyska** [comment]
@BirjuVachhani can you update this package?

**Comment by dan-gandolfo** [comment]
Any one has fork it?

**Comment by mr-mmmmore** [comment]
There are few forks that have done the migration to null safety, I have been using the one from [Insight-Timer](https://github.com/Insight-Timer/flutter_phone_state) but have encountered some bugs, so I forked it to fix it. You can find it here: [https://github.com/mr-mmmmore/flutter_phone_state/tree/fixes](https://github.com/mr-mmmmore/flutter_phone_state), be sure to use the `fixes` branch where I have committed my changes. You may create an issue if you find one but **use at your own risk** as I don't have time to provide any support.

**Comment by BirjuVachhani** [comment]
@hanyska I have this migrated branch here:
https://github.com/SimformSolutionsPvtLtd/flutter_phone_state/tree/feature/null-safety

However it is not tested!

**Comment by dan-gandolfo** [comment]
Thanks for your answers.. I will try to work with your branch.

**Comment by EgHubs** [comment]
Help please @mr-mmmmore or anyone,
I've tried these forks (Insight-Timer/master, mr-mmmmore/fixes)and I get this error
```
I/flutter (13544): calling 0100000000
[flutterPhoneState] Error handling native event type 'Null' is not a subtype of type 'String' in type cast
                    type 'Null' is not a subtype of type 'String' in type cast
                    #0      _initializedNativeEvents.<anonymous closure> (package:flutter_phone_state/flutter_phone_state.dart:224:40)
                    #1      _MapStream._handleData (dart:async/stream_pipe.dart:213:31)
                    #2      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
                    #3      _rootRunUnary (dart:async/zone.dart:1362:47)
                    #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
                    #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
                    #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
                    #7      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
                    #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
                    #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
                    #10     _rootRun (dart:async/zone.dart:1346:47)
                    #11     _CustomZone.run (dart:async/zone.dart:1258:19)
                    #12     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
                    #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
                    #14     _rootRun (dart:async/zone.dart:1354:13)
                    #15     _CustomZone.run (dart:async/zone.dart:1258:19)
                    #16     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
                    #17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
                    #18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
                    #19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[flutterPhoneState] Received application lifecycle state change: AppLifecycleState.inactive
[flutterPhoneState] Received application lifecycle state change: AppLifecycleState.paused

```

this is my code
```
TextButton(
                          child: Text('click me'),
                          onPressed: () async {
                            PhoneCall? initiatedPhoneCall;
                            String phoneNumber="0100000000";
                              initiatedPhoneCall =
                                  FlutterPhoneState.startPhoneCall(
                                      phoneNumber);
                              print('calling $phoneNumber');
                              await initiatedPhoneCall.done;
                          },
                        )
```

the phone app appears and the number is written without calling and I get that error
